### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by aswanijeet1412**

### CODE REVIEW

**Comment by yangl1996** [comment]
Hi there - is there anything particular you'd like to contribute to the project? Or, are you editing your own website?

**Comment by aswanijeet1412** [comment]
Hey Lei,

Actually, I am struggling to edit my own website.

I create the website but getting a problem in changing the framework.

https://jitendra-aswani.netlify.app/

I believe I have to change the "index.html" file, but I could not able to
change it.

If possible, can you please help me with it or teach me how to do it?

Thank you.

Regards,
Jeet




On Wed, Feb 3, 2021 at 4:48 PM Lei Yang <notifications@github.com> wrote:

> Hi there - is there anything particular you'd like to contribute to the
> project? Or, are you editing your own website?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_yangl1996_academimal_pull_2-23issuecomment-2D772846773&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=sDsgflkRFvLZ9LhVcVqgx1bHKX2SqwbqHPgVc1A8Yow&m=rF10BD_GXR9tiTy2Esfwcf7J3Q7N3ltnPm2gmMKP0d4&s=k2mndVKly5Hxj6GqT0QA549taeey4vAxVDfYxgUgagQ&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKZHUPJ2OPBYFWNDQT6EKZTS5HAC3ANCNFSM4XBPHIOA&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=sDsgflkRFvLZ9LhVcVqgx1bHKX2SqwbqHPgVc1A8Yow&m=rF10BD_GXR9tiTy2Esfwcf7J3Q7N3ltnPm2gmMKP0d4&s=Mz1YCfgFMtZzRgB9gLg6lFUIYDH906LVS8oVU57SYPU&e=>
> .
>


-- 
Regards,
*Jitendra Aswani*
Ph.D. Student
Gabelli School of Business
Fordham University
Ph: *+1- (646) 247 9638*


"*If you are willing to do only what's easy, life will be hard. But if you
are willing to do what's hard, life will be easy*” - T. Harv Eker.

"*Dripping water hollows out stone, not through force but through
persistence*" - Ovid, Roman Poet.

"*Winning isn't everything, it's the only thing*" - Vince Lombardi,
American football player.

"*Just because your muscles start to protest, doesn't mean you have to
listen"* - Dianne Holum, American speed skater.

**Comment by yangl1996** [comment]
Hi Jeet, thanks for your interest! This documentation may be useful https://gohugo.io/templates/. You may also want to check how [Hugo](https://gohugo.io) works in general and how to deploy a Hugo site.

**Comment by aswanijeet1412** [comment]
Thanks, Lei.

Problem solved.

Regards,
Jeet

On Thu, Feb 4, 2021 at 5:06 PM Lei Yang <notifications@github.com> wrote:

> Hi Jeet, thanks for your interest! This documentation may be useful
> https://gohugo.io/templates/
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__gohugo.io_templates_&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=sDsgflkRFvLZ9LhVcVqgx1bHKX2SqwbqHPgVc1A8Yow&m=cirSAo30tzizthaFnNbdAJyU2uBQkUK3BplZRQmYlKw&s=8mkadkvhrv1WhOkLZmVGDkOZpf1wXvQWF7guxN_1dC8&e=>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_yangl1996_academimal_pull_2-23issuecomment-2D773634150&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=sDsgflkRFvLZ9LhVcVqgx1bHKX2SqwbqHPgVc1A8Yow&m=cirSAo30tzizthaFnNbdAJyU2uBQkUK3BplZRQmYlKw&s=uKY1sl9tP2pWMCEQ4sY5qkPDkiiqAc-RJKTH4xBJrCA&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKZHUPP6BK4KHMPGN6QLYDTS5MK5DANCNFSM4XBPHIOA&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=sDsgflkRFvLZ9LhVcVqgx1bHKX2SqwbqHPgVc1A8Yow&m=cirSAo30tzizthaFnNbdAJyU2uBQkUK3BplZRQmYlKw&s=n_JOal51RESY2yfkB2VnEkfsh7EO-5hMzGZTc78aAss&e=>
> .
>


-- 
Regards,
*Jitendra Aswani*
Ph.D. Student
Gabelli School of Business
Fordham University
Ph: *+1- (646) 247 9638*


"*If you are willing to do only what's easy, life will be hard. But if you
are willing to do what's hard, life will be easy*” - T. Harv Eker.

"*Dripping water hollows out stone, not through force but through
persistence*" - Ovid, Roman Poet.

"*Winning isn't everything, it's the only thing*" - Vince Lombardi,
American football player.

"*Just because your muscles start to protest, doesn't mean you have to
listen"* - Dianne Holum, American speed skater.

**Pull request closed without merging**
